### ISSUE TITLE
error when import tpl 

### ISSUE THREAD

**Issue by opera443399** [endersonmaia/zabbix-templates#1]
some items have defined "valuemap", which not provided here.

please provide this: "CONFIGURATION OF VALUE MAPPING"

thank you

tested on zabbix version:
2.2.3
2.4.6

**Comment by opera443399** [comment]
1) Cannot find value map "DellPowerState" used for item "Overall System Power State" on "Template Dell iDrac SNMPV2".
Line 393

![11](https://cloud.githubusercontent.com/assets/13327561/9484822/ba81ff08-4be3-11e5-8538-5fe89f1a8113.png)

**Comment by opera443399** [comment]
2)Cannot find value map "DellDracDiskState" used for item prototype "Disk {#SNMPINDEX} : Disk State" of discovery rule "Disk Enumeration" on "Template Dell iDrac SNMPV2".

Line: 1089

**Comment by opera443399** [comment]
3)Cannot find value map "DellRaidLevel" used for item prototype "Volume {#SNMPINDEX} : State" of discovery rule "Disk Volume Enumeration" on "Template Dell iDrac SNMPV2".

Line: 1614

**Comment by opera443399** [comment]
4) Cannot find value map "DellRaidVolumeState" used for item prototype "Volume {#SNMPINDEX} : Virtual Disk State" of discovery rule "Disk Volume Enumeration" on "Template Dell iDrac SNMPV2".

Line: 1704

**Comment by opera443399** [comment]
5) Cannot find value map "Dell iDRAC Network Device Connection Status" used for item prototype "NIC {#SNMPINDEX} : Connection Status" of discovery rule "Network Enumeration" on "Template Dell iDrac SNMPV2".

Line: 2283

**Comment by opera443399** [comment]
6) Cannot find value map "Dell_PSU_SensorState" used for item prototype "Power Supply {#SNMPINDEX} Sensor State" of discovery rule "Power Supply Enumeration" on "Template Dell iDrac SNMPV2".

Line: 2645

**Comment by opera443399** [comment]
7) Cannot find value map "Dell PSU State Settings" used for item prototype "Power Supply {#SNMPINDEX} State Settings" of discovery rule "Power Supply Enumeration" on "Template Dell iDrac SNMPV2".

Line: 2690

**Comment by opera443399** [comment]
that's all I found.

**Comment by endersonmaia** [comment]
You'll need to create all the Value Mappings, see this for reference: https://www.zabbix.com/forum/showpost.php?p=146120&postcount=15
