### ISSUE TITLE
NIC status on both iDrac7 and iDrac8

### ISSUE THREAD

**Issue by hetzbh** [endersonmaia/zabbix-templates#5]
Hi,
I'm using this great template on both iDrac 7 and iDrac 8 machines from Dell, and there's a small issue: it shows the NICs as "Down" when they are actually connected and up.

Could it be wrong value mapping? 
I enclose a screenshot,

[screenshot-zabbix 2016-07-11 13-07-43](https://cloud.githubusercontent.com/assets/8313341/16727195/9f139962-4768-11e6-9655-e2da5adbffec.png)

**Comment by endersonmaia** [comment]
Yes, that's a Value Mapping problem, I'll fix the README.
